version: '2'

services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      # - REDIS_PASSWORD=test
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data:
    driver: local